"""
AI Stock Analyzer - AI Service
Orkestrasi pemanggilan AI: ambil data, buat prompt, panggil Claude, dan simpan hasilnya.
"""

import logging
from datetime import date
import pandas as pd
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.models.models import DailyPrice, TechnicalIndicator, AIAnalysis
from app.services.prompt_builder import build_analysis_prompt
from app.infrastructure.ai_client import call_claude_sonnet

logger = logging.getLogger(__name__)

async def run_ai_analysis(ticker: str, db: AsyncSession) -> dict:
    """
    Menjalankan end-to-end proses AI untuk satu saham.
    1. Ambil 10 data daily price terakhir dari DB
    2. Ambil technical indicator terakhir dari DB
    3. Generate prompt dan panggil Claude
    4. Simpan ke database (tabel ai_analyses)
    """
    logger.info(f"Memulai AI Analysis untuk saham {ticker}")
    
    # 1. Ambil 10 harga terakhir
    stmt_price = (
        select(DailyPrice)
        .where(DailyPrice.stock_ticker == ticker)
        .order_by(DailyPrice.trading_date.desc())
        .limit(10)
    )
    result_price = await db.execute(stmt_price)
    prices = result_price.scalars().all()
    
    if not prices:
        raise ValueError(f"Tidak ada data harga untuk {ticker}")
    
    # Urutkan dari terlama ke terbaru (untuk dataframe)
    prices = list(reversed(prices))
    df = pd.DataFrame([{
        "trading_date": p.trading_date,
        "open": float(p.open),
        "high": float(p.high),
        "low": float(p.low),
        "close": float(p.close),
        "volume": p.volume,
    } for p in prices])
    
    # 2. Ambil technical indicator 5 hari terakhir
    stmt_tech = (
        select(TechnicalIndicator)
        .where(TechnicalIndicator.stock_ticker == ticker)
        .order_by(TechnicalIndicator.trading_date.desc())
        .limit(5)
    )
    result_tech = await db.execute(stmt_tech)
    techs = list(reversed(result_tech.scalars().all()))
    
    if not techs:
        raise ValueError(f"Tidak ada data indikator teknikal untuk {ticker}")
        
    latest_tech = techs[-1]
    
    # Gabungkan data technical indicator ke dataframe
    tech_map = {t.trading_date: t for t in techs}
    for col in ['rsi_14', 'ema_50', 'ema_200', 'stopping_volume', 'no_demand', 'climactic_volume']:
        df[col] = df['trading_date'].apply(lambda d: getattr(tech_map.get(d), col, None) if d in tech_map else None)

    latest_indicators_dict = {
        "smc_patterns": latest_tech.smc_patterns,
        "is_spring": latest_tech.is_spring,
        "wyckoff_phase": latest_tech.wyckoff_phase
    }
    
    # 3. Build Prompt
    system_prompt, user_prompt = build_analysis_prompt(ticker, df, latest_indicators_dict)
    
    # 4. Call Claude
    ai_response = await call_claude_sonnet(system_prompt, user_prompt)
    
    # 5. Parse and Save to Database
    recommendation = ai_response.get("recommendation", "HOLD").upper()
    if recommendation not in ["BUY", "HOLD", "WAIT"]:
        recommendation = "HOLD"
        
    conf_score_raw = ai_response.get("confidence_score", 0.0)
    try:
        conf_score = int(float(conf_score_raw) * 100)
    except (ValueError, TypeError):
        conf_score = 0
        
    analysis_date = latest_tech.trading_date
    
    # Cek apakah sudah ada analisis hari ini
    stmt_check = select(AIAnalysis).where(
        AIAnalysis.stock_ticker == ticker,
        AIAnalysis.analysis_date == analysis_date
    )
    result_check = await db.execute(stmt_check)
    existing = result_check.scalars().first()
    
    if existing:
        existing.wyckoff_phase_ai = ai_response.get("wyckoff_phase", "")
        existing.vpa_insight = ai_response.get("vpa_insight", "")
        existing.recommendation = recommendation
        existing.confidence_score = conf_score
        existing.ai_summary = "Generated by Claude Sonnet"
        existing.tokens_used = ai_response.get("tokens_used", 0)
    else:
        new_analysis = AIAnalysis(
            stock_ticker=ticker,
            analysis_date=analysis_date,
            wyckoff_phase_ai=ai_response.get("wyckoff_phase", ""),
            vpa_insight=ai_response.get("vpa_insight", ""),
            recommendation=recommendation,
            confidence_score=conf_score,
            ai_summary="Generated by Claude Sonnet",
            tokens_used=ai_response.get("tokens_used", 0)
        )
        db.add(new_analysis)
        
    await db.commit()
    logger.info(f"AI Analysis untuk {ticker} sukses disimpan.")
    
    return ai_response
