"""add analyzed by to ai_analyses

Revision ID: ijkl5678mnop
Revises: abcd1234efgh
Create Date: 2026-07-29 08:12:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ijkl5678mnop'
down_revision = 'abcd1234efgh'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('analyzed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ai_analyses', 'users', ['analyzed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_analyses', type_='foreignkey')
    op.drop_column('ai_analyses', 'analyzed_by')
    # ### end Alembic commands ###
