"""Alembic migration script template."""
# revision identifiers, used by Alembic.
revision = '3d9f007bf6ad'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('analysis_quota_used', sa.Integer(), nullable=False),
    sa.Column('last_quota_reset', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_ticker', sa.String(length=20), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('vpa_insight', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('wyckoff_phase_ai', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_analysis_date'), 'ai_analyses', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_ai_analyses_stock_ticker'), 'ai_analyses', ['stock_ticker'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stock_ticker', sa.String(length=20), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_prices_stock_ticker'), 'daily_prices', ['stock_ticker'], unique=False)
    op.create_index(op.f('ix_daily_prices_trading_date'), 'daily_prices', ['trading_date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stock_ticker', sa.String(length=20), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('rsi_14', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ema_20', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('ema_200', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.Column('stopping_volume', sa.Boolean(), nullable=False),
    sa.Column('no_demand', sa.Boolean(), nullable=False),
    sa.Column('is_spring', sa.Boolean(), nullable=False),
    sa.Column('climactic_volume', sa.Boolean(), nullable=False),
    sa.Column('wyckoff_phase', sa.String(length=20), nullable=True),
    sa.Column('smc_patterns', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stock_ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_indicators_stock_ticker'), 'technical_indicators', ['stock_ticker'], unique=False)
    op.create_index(op.f('ix_technical_indicators_trading_date'), 'technical_indicators', ['trading_date'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_ticker', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_technical_indicators_trading_date'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_stock_ticker'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_daily_prices_trading_date'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_stock_ticker'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_ai_analyses_stock_ticker'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_date'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
